#!/usr/bin/env bash

# Symbolic link with .dotfiles to ~/$HOME directory
find "$(pwd)" -name ".*" -type f -maxdepth 1 | xargs -I '{}' ln -s '{}' ~

# Ignore system/custom.sh file. http://stackoverflow.com/a/653495/462015
git update-index --skip-worktree system/custom.sh

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install formulas
brew install docker docker-machine docker-compose

brew install git
brew install homebrew/versions/bash-completion2
brew install hr
brew install htop-osx
brew install httpie
brew install tree
brew install wget
brew install ansible
brew install coreutils
brew install freetype
brew install imagemagick
brew install node
brew install phantomjs
brew install readline
brew install youtube-dl
brew install ant
brew install dos2unix
brew install openssl
brew install chromedriver
brew install ffmpeg
brew install lame
brew install python

# Brew GUI Mac applications
brew install caskroom/cask/brew-cask
brew cask install alfred
brew cask install postgres
brew cask install calibre
brew cask install chitchat
brew cask install dropbox
brew cask install skitch
brew cask install gimp
brew cask install google-chrome
brew cask install iterm2
brew cask install java
brew cask install visualvm
brew cask install macdown
brew cask install intellij-idea
brew cask install hipchat
brew cask install spotify
brew cask install the-unarchiver
brew cask install virtualbox
brew cask install vlc
brew cask install 1password
brew cask install appdelete
brew cask install postman
brew cask install cyberduck
brew cask install disk-inventory-x
brew cask install firefox
brew cask install github-desktop
brew cask install macs-fan-control
brew cask install microsoft-office
brew cask install stremio
brew cask install sublime-text
brew cask install textmate

# Bash 4 in OS X
brew install bash
sudo echo $(brew --prefix)/bin/bash >> /etc/shells
chsh -s $(brew --prefix)/bin/bash

# Prevent Time Machine from prompting to use new hard drives as backup volume
#defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable creation of metadata files on network volumes
#defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable creation of metadata files on USB volumes
#defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Change screenshots format
defaults write com.apple.screencapture type png

# Install all available software updates
sudo softwareupdate -ia
